# Generated by Django 4.2.30 on 2026-07-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent', verbose_name='konten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemember', verbose_name='anggota')),
            ],
            options={
                'verbose_name': 'Progress Pelajaran',
                'verbose_name_plural': 'Progress Pelajaran',
                'unique_together': {('member', 'content')},
            },
        ),
    ]
